travis:
  secure:
    BINSTAR_TOKEN: kMpvjix+cJelukb6z5STUNF98ouqDEGrPR4r6/eYPDWMlULE7koOIl5O10QQA6lOBGmGD7KZCqanNnyCUx+OKZw24HLWDM/Uwwv+Biu+ExxpWtjftzHUZ/xdUBSqMqgTvgJLH+L/pj8sWcotQgaEztiRw/rlXlzwxnluR08gGxu7OXyjqxw+Ux5wbpD3yWDrbwgQxIEG55AqhVS8HGNOMFDIpC4mZri0mMgDGR0xBzY60tkKK2s5ApWfg6bT2C47WyoeIh80S1xuVvbGw6U9cis4ZNzHnBVyL61qWLswVNW4VlqY5uzCHw3kUDejjBEb/ME9oQJOtP/8PMkEcmDOxMGvaWx14T174Vn8THsRc/vetu8QIfqPL+6DtD+sFX0FdJ5bTjhujzZNl8dzkamHiYB7uZ34ubbYqtbxObEDYV4yEn19B6zQF1MnGNeWmAICZtQShRSb2ariQlLy7tNEcZVxPp8kG0B91z0/FjpANQO7fYeQdTbOS6kh4LRABdHbh1U2eJLZyt3vdCfqOlmmnbofugFEcEjSphRgb1pr7PXx94cWf8hIOXjVt8fJSrQu+T/mAR3LQKWv3khS3dmaqX0EvxcGFa4xK38AXQk0uXpfEyiIZJNBPek4MgoUYce++2vGL/cuhxY+V4AxJypPxSHG7mCJDsW3s95Y4S+ydGI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
